### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jigarius** [jigarius/toggl2redmine#52]
## To-do

- [x] Setup GitHub workflow
- [x] Create Docker-based dev env setup
  - [x] Provide helper commands in `Rakefile`
- [x] Create seed data for testing and development
- [x] Create unit tests for models
  - [x] `TogglTimeEntry`
  - [x] `TogglWorkspace`
  - [x] `TogglTimeEntryGroup`
  - [x] `TogglMapping`
  - [x] `TogglService`
- [x] Create integration tests for controllers
  - [x] `T2rBaseController`
  - [x] `T2rImportController`
  - [x] `T2rRedmineController`
  - [x] `T2rTogglController`

**Comment by jigarius** [comment]
Configured automated test execution with Travis. Currently, there's only one placeholder test to check if `1 == 1` 😅 I hope I can add some real tests soon.

**Comment by jigarius** [comment]
## Dev env setup

* Set up docker-compose for easily building local dev envs
  * Probably, docker-compose can be used for the CI test env as well?
  * Next step: Cleanup and commit the docker-compose stuff into a `.deploy` directory
* Created `db/seeds.rb` to create dummy data for dev envs
  * Simply, put the file in `redmine/db/seeds.rb` and run `rake db:seed` to import test data

**Comment by jigarius** [comment]
Having worked with Redmine tests, I can say that I've seen it all as a developer 😓 .

  * `UserCustomField` for _Toggl API Token_ gets deleted during tests for some reason?
  * Test routes added using `Rails.application.routes.append` in `setup {}` don't get recognized during the tests.
    * I created a test route in `routes.rb` and wrapped it in a `if Rails.env == 'test'`.

Now that the `T2rBaseController` is out of the way, the rest should be relatively simple.
